Updated, rebranded.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3522,8 +3522,8 @@ fi
 
 
 if test $ac_cv_header_sys_ipc_h = no; then
-	{ { echo "$as_me:$LINENO: error: Cannot find required header file sys/ipc.h; XCurses cannot be configured" >&5
-echo "$as_me: error: Cannot find required header file sys/ipc.h; XCurses cannot be configured" >&2;}
+	{ { echo "$as_me:$LINENO: error: Cannot find required header file sys/ipc.h; PDCurses cannot be configured" >&5
+echo "$as_me: error: Cannot find required header file sys/ipc.h; PDCurses cannot be configured" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
@@ -4542,16 +4542,16 @@ if test "x$mh_x11_dir" != "x" ; then
 		MH_XINC_DIR="-I$mh_x11_dir"
 	fi
 else
-	{ { echo "$as_me:$LINENO: error: Cannot find required header file Intrinsic.h; XCurses cannot be configured" >&5
-echo "$as_me: error: Cannot find required header file Intrinsic.h; XCurses cannot be configured" >&2;}
+	{ { echo "$as_me:$LINENO: error: Cannot find required header file Intrinsic.h; PDCurses cannot be configured" >&5
+echo "$as_me: error: Cannot find required header file Intrinsic.h; PDCurses cannot be configured" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
 if test "x$mh_x11_xaw_dir" != "x" ; then
 	MH_XINC_DIR="-I$mh_x11_xaw_dir $MH_XINC_DIR"
 else
-	{ { echo "$as_me:$LINENO: error: Cannot find required Xaw header file Box.h; XCurses cannot be configured" >&5
-echo "$as_me: error: Cannot find required Xaw header file Box.h; XCurses cannot be configured" >&2;}
+	{ { echo "$as_me:$LINENO: error: Cannot find required Xaw header file Box.h; PDCurses cannot be configured" >&5
+echo "$as_me: error: Cannot find required Xaw header file Box.h; PDCurses cannot be configured" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
@@ -4681,8 +4681,8 @@ for mh_lib in $mh_libs; do
     done
   done
   if test "$mh_lib_found" = no; then
-    { { echo "$as_me:$LINENO: error: Cannot find required X library; lib$mh_lib. XCurses cannot be configured" >&5
-echo "$as_me: error: Cannot find required X library; lib$mh_lib. XCurses cannot be configured" >&2;}
+    { { echo "$as_me:$LINENO: error: Cannot find required X library; lib$mh_lib. PDCurses cannot be configured" >&5
+echo "$as_me: error: Cannot find required X library; lib$mh_lib. PDCurses cannot be configured" >&2;}
    { (exit 1); exit 1; }; }
   fi
 done
